const data = {
  products: [
    {
      // _id : 1,
      name: 'VANILLA STRAWBERRY',
      slug: 'f0',
      category: 'vanilla',
      image: '/flavors/f-0.png', // 679px × 829px
      price: 7.99,
      countInStock: 0,
      brand: 'smoke',
      rating: 4.5,
      numReviews: 10,
      description: 'As sweet as a dessert. Make the most of the blending of the strawberry and vanilla for a delectable flavor',
    },
    {
      // _id : 2,
      name: 'BLUEBERRY RASBERRY',
      slug: 'f1',
      category: 'BLUEBERRY',
      image: '/flavors/f-1.png',
      price: 7.99,
      countInStock: 20,
      brand: 'smoke',
      rating: 4.0,
      numReviews: 10,
      description: 'It feels like being on a farm, where the fresh flavors of freshly harvested blueberries and raspberries are distilled into the perfect flavor',
    },
    {
      // _id : 3,
      name: 'RASPBERRY GRAPE SHERBET',
      slug: 'f2',
      category: 'RASPBERRY',
      image: '/flavors/f-2.png',
      price: 7.99,
      countInStock: 15,
      brand: 'Smoke',
      rating: 4.5,
      numReviews: 14,
      description: 'A refreshing taste of freshly picked juicy grapes and raspberries with a tangy refreshing sherbet',
    },
    {
      // _id : 4,
      name: 'WATERMELON ICE',
      slug: 'f3',
      category: 'WATERMELON',
      image: '/flavors/f-3.png',
      price: 7.99,
      countInStock: 5,
      brand: 'smoke',
      rating: 4.5,
      numReviews: 10,
      description: 'A fusion of sweet watermelon candy flavor and a fresh breeze of menthol.',
    },
    {
      // _id : 4,
      name: 'BLUEBERRY ICE',
      slug: 'f4',
      category: 'BLUEBERRY',
      image: '/flavors/f-4.png',
      price: 7.99,
      countInStock: 5,
      brand: 'smoke',
      rating: 4.5,
      numReviews: 10,
      description: 'The fragrance of blueberry mixed with cooling menthol, fruity and refreshing',
    },
    {
      // _id : 4,
      name: 'BLUEBERRY LEMON',
      slug: 'f5',
      category: 'BLUEBERRY',
      image: '/flavors/f-5.png',
      price: 7.99,
      countInStock: 5,
      brand: 'smoke',
      rating: 4.5,
      numReviews: 10,
      description: 'A mouthwatering flavor rises from the medley of tart blueberry and tangy lemon',
    },
    {
      // _id : 4,
      name: 'PEACH APPLE',
      slug: 'f6',
      category: 'PEACH',
      image: '/flavors/f-6.png',
      price: 7.99,
      countInStock: 5,
      brand: 'smoke',
      rating: 4.5,
      numReviews: 10,
      description: 'A dominant pineapple blended with sweet peaches.',
    },
    {
      // _id : 4,
      name: 'STRAWBERRY WATERMELON',
      slug: 'f7',
      category: 'STRAWBERRY',
      image: '/flavors/f-7.png',
      price: 7.99,
      countInStock: 5,
      brand: 'smoke',
      rating: 4.5,
      numReviews: 10,
      description: 'It seems that you are tasting the flavor of summer, juicy and sweet.',
    },
    {
      // _id : 4,
      name: 'RAGING BULL',
      slug: 'f8',
      category: 'RAGING',
      image: '/flavors/f-8.png',
      price: 7.99,
      countInStock: 5,
      brand: 'smoke',
      rating: 4.5,
      numReviews: 10,
      description: 'Somewhere to relieve fatigue and clear your mind.',
    },
    {
      // _id : 4,
      name: 'PINK LEMONADE',
      slug: 'f9',
      category: 'PINK',
      image: '/flavors/f-9.png',
      price: 7.99,
      countInStock: 5,
      brand: 'smoke',
      rating: 4.5,
      numReviews: 10,
      description: 'The tangy lemon collides with crushed strawberries,leaving you with a lingering fragrance.',
    },
    {
      // _id : 4,
      name: 'PEACH PINEAPPLE',
      slug: 'f10',
      category: 'PEACH',
      image: '/flavors/f-10.png',
      price: 7.99,
      countInStock: 5,
      brand: 'smoke',
      rating: 4.5,
      numReviews: 10,
      description: 'A dominant pineapple blended with sweet peaches. ',
    },
    {
      // _id : 4,
      name: 'PEACH GRAPE',
      slug: 'f11',
      category: 'PEACH',
      image: '/flavors/f-11.png',
      price: 7.99,
      countInStock: 5,
      brand: 'smoke',
      rating: 4.5,
      numReviews: 10,
      description: 'The juicy grape complemented brilliantly with sweet peach.',
    },
    {
      // _id : 4,
      name: 'CHERRY LEMON PEACH',
      slug: 'f12',
      category: 'PEACH',
      image: '/flavors/f-12.png',
      price: 7.99,
      countInStock: 5,
      brand: 'smoke',
      rating: 4.5,
      numReviews: 10,
      description: 'Offer a mixture of tart cherries, juicy peaches and fresh lemons made with simple and clean ingredients.',
    },
    {
      // _id : 4,
      name: 'MIXED BERRIES',
      slug: 'f13',
      category: 'MIXED',
      image: '/flavors/f-13.png',
      price: 7.99,
      countInStock: 5,
      brand: 'smoke',
      rating: 4.5,
      numReviews: 10,
      description: 'Brimming with sugary sweetness and fragrance of blueberry',
    },
    {
      // _id : 4,
      name: 'BLUEBERRY BLASTING',
      slug: 'f14',
      category: 'BLUEBERRY',
      image: '/flavors/f-14.png',
      price: 7.99,
      countInStock: 5,
      brand: 'smoke',
      rating: 4.5,
      numReviews: 10,
      description: 'The fruity blueberry softens the strong coolness and the latter neutralizes the sweetness of the former for a refined taste',
    },
  ],
};
module.exports =  data;